### ISSUE TITLE
autostart flow server

### ISSUE THREAD

**Issue by nhooyr** [steelsojka/deoplete-flow#8]
This plugin doesn't seem to work unless I manually start the flow server.

**Comment by codemonkey800** [comment]
Not the author, but looks like it's because the `autocomplete` subcommand is called with the `--no-auto-start`, so deoplete can't gather sources unless the server is started manually.

[The line is here.](https://github.com/steelsojka/deoplete-flow/blob/master/rplugin/python3/deoplete/sources/flow.py#L28)

It could be an oversight or maybe it's so you have to manually start the server. They should at least document it if it has to be started manually.

**Comment by steelsojka** [comment]
@nhooyr You do manually have to start the server. Since deoplete calls that function multiple times an error would occur if the server was already running and you didn't specify not to auto start it. This was the cause at the time of writing the plugin. I haven't used flow in some time and have not kept update to date with API changes. 

I have been busy and haven't been able to keep up with many changes. If you get this working with auto start, please submit a PR 👍

**Comment by nhooyr** [comment]
Going to close as it has been a long time and I'm not sure if this is relevant anymore.
